### ISSUE TITLE
bazel build is currently broken

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp-spanner#101]
@devjgm reported this was working for him this morning, but @scotthart and I are both seeing errors curently.

The cmake docker build (`./ci/kokoro/docker/build.sh cmake`) still works.

```
ERROR: /usr/local/google/home/salty/.cache/bazel/_bazel_salty/a06bf7d6e7b5baf005af3692f783e8ad/external/com_google_googleapis/google/longrunning/BUILD.bazel:107:1: in _generate_cc rule @com_google_googleapis//google/longrunning:_longrunning_cc_grpc_grpc_codegen: 
Traceback (most recent call last):
	File "/usr/local/google/home/salty/.cache/bazel/_bazel_salty/a06bf7d6e7b5baf005af3692f783e8ad/external/com_google_googleapis/google/longrunning/BUILD.bazel", line 107
		_generate_cc(name = '_longrunning_cc_grpc_grpc_codegen')
	File "/usr/local/google/home/salty/.cache/bazel/_bazel_salty/a06bf7d6e7b5baf005af3692f783e8ad/external/com_github_grpc_grpc/bazel/generate_cc.bzl", line 44, in generate_cc_impl
		[f for src in ctx.attr.srcs for f in src.proto.check_deps_sources]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
INFO: Call stack for the definition of repository 'remotejdk11_linux' which is a http_archive (rule definition at /usr/local/google/home/salty/.cache/bazel/_bazel_salty/a06bf7d6e7b5baf005af3692f783e8ad/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /DEFAULT.WORKSPACE.SUFFIX:199:1
ERROR: /usr/local/google/home/salty/.cache/bazel/_bazel_salty/a06bf7d6e7b5baf005af3692f783e8ad/external/com_google_googleapis/BUILD.bazel:34:1: in _generate_cc rule @com_google_googleapis//:_grpc_spanner_proto_grpc_codegen: 
Traceback (most recent call last):
	File "/usr/local/google/home/salty/.cache/bazel/_bazel_salty/a06bf7d6e7b5baf005af3692f783e8ad/external/com_google_googleapis/BUILD.bazel", line 34
		_generate_cc(name = '_grpc_spanner_proto_grpc_codegen')
	File "/usr/local/google/home/salty/.cache/bazel/_bazel_salty/a06bf7d6e7b5baf005af3692f783e8ad/external/com_github_grpc_grpc/bazel/generate_cc.bzl", line 44, in generate_cc_impl
		[f for src in ctx.attr.srcs for f in src.proto.check_deps_sources]
type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
ERROR: Analysis of target '//google/cloud/spanner:spanner_client' failed; build aborted: Analysis of target '@com_google_googleapis//:_grpc_spanner_proto_grpc_codegen' failed; build aborted
INFO: Elapsed time: 0.211s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets conf\
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets conf\
igured)
```

**Comment by coryan** [comment]
The CI builds are using Bazel 0.24.0, you are probably using Bazel 0.27.0. The patch below reproduces the problems you are seeing.  "Live at Head" for the "win".

```patch
diff --git a/ci/install-bazel.sh b/ci/install-bazel.sh
index 98d62a8..50a8d16 100755
--- a/ci/install-bazel.sh
+++ b/ci/install-bazel.sh
@@ -18,7 +18,7 @@ set -eu
 readonly PLATFORM=$(printf "%s-%s" "$(uname -s)" "$(uname -m)" \
   |  tr '[:upper:]' '[:lower:]')
 
-readonly BAZEL_VERSION="0.24.0"
+readonly BAZEL_VERSION="0.27.0"
 readonly GITHUB_DL="https://github.com/bazelbuild/bazel/releases/download"
 readonly SCRIPT_NAME="bazel-${BAZEL_VERSION}-installer-${PLATFORM}.sh"
 wget -q "${GITHUB_DL}/${BAZEL_VERSION}/${SCRIPT_NAME}"
```

**Comment by devjgm** [comment]
Thanks for the report.

As the "operator", I'll take a look at why 0.27 broke us.

**Comment by devjgm** [comment]
Yep, it looks bazel 0.27, which was released about 7 hours ago, broke us. There will always be some cases where bazel (or other things) are updated and break us. It seems the only way to avoid this is to do hermetic-ish builds, as as the builds we do in docker now.

So I think the best path forward is for us use `./ci/kokoro/docker/build.sh <config>` to run our builds, even during development. For example, to build using cmake, run

```
$ ./ci/kokoro/docker/build.sh cmake
```

And to build using bazel, you can use any of the build modes that use bazel, such as:

```
$ ./ci/kokoro/docker/build.sh asan
```

Note: We could also add a new build mode named like `./ci/kokoro/docker/build.sh bazel`, if we think that's necessary. I'm not opposed to it, but I also don't see the need.

**Comment by tmatsuo** [comment]
FYI on the Windows Bazal build uses Bazel 0.28.1 and the build passed at least few times yesterday.

**Comment by remyabel** [comment]
The issue (which has already been fixed) was that gRPC needed to be updated along side updating Bazel to 0.28.0. Should the Windows version use the same version for consistency?

**Comment by tmatsuo** [comment]
We needed Bazel 0.25 or higher for Visual Studio 2019, so I jumped to the latest version.

**Comment by remyabel** [comment]
What I'm saying is we should use either 0.28.0 or 0.28.1 for all the builds for consistency.

**Comment by tmatsuo** [comment]
Gotcha. Personally I'm fine with the inconsistency here, but in a long run we should somehow follow Bazel version. This might be  a good candidate for stuff like rennovate?
